version: '3'
services:
  nginx:
    image: nginx:1.18
    ports:
      - 8088:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD:/code

  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $PWD:/code
